// Store configuration with brand colors (no external image URLs)
export const STORES = {
  walmart: {
    id: "walmart",
    name: "Walmart",
    color: "#0071CE",
    adapter: "walmart",
    supports_pricing: true,
    supports_products: true,
    supports_export: true,
  },
  kroger: {
    id: "kroger",
    name: "Kroger",
    color: "#C8102E",
    adapter: "kroger",
    supports_pricing: true,
    supports_products: true,
    supports_export: true,
  },
  harris_teeter: {
    id: "harris_teeter",
    name: "Harris Teeter",
    color: "#006B3C",
    adapter: "kroger",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  food_lion: {
    id: "food_lion",
    name: "Food Lion",
    color: "#E31837",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  sams_club: {
    id: "sams_club",
    name: "Sam's Club",
    color: "#003087",
    adapter: "walmart",
    supports_pricing: true,
    supports_products: true,
    supports_export: true,
  },
  meijer: {
    id: "meijer",
    name: "Meijer",
    color: "#003DA5",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  heb: {
    id: "heb",
    name: "H-E-B",
    color: "#E31837",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  albertsons: {
    id: "albertsons",
    name: "Albertsons",
    color: "#0057A6",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  sprouts: {
    id: "sprouts",
    name: "Sprouts",
    color: "#007B40",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  trader_joes: {
    id: "trader_joes",
    name: "Trader Joe's",
    color: "#BB1F2A",
    adapter: "metadata-only",
    supports_pricing: false,
    supports_products: false,
    supports_export: false,
  },
  winco: {
    id: "winco",
    name: "WinCo Foods",
    color: "#2D6A2D",
    adapter: "metadata-only",
    supports_pricing: false,
    supports_products: false,
    supports_export: false,
  },
  aldi: {
    id: "aldi",
    name: "Aldi",
    color: "#00005F",
    adapter: "metadata-only",
    supports_pricing: false,
    supports_products: false,
    supports_export: false,
  },
  giant: {
    id: "giant",
    name: "Giant",
    color: "#CC0000",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  giant_eagle: {
    id: "giant_eagle",
    name: "Giant Eagle",
    color: "#005A9C",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  hy_vee: {
    id: "hy_vee",
    name: "Hy-Vee",
    color: "#E31837",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  wegmans: {
    id: "wegmans",
    name: "Wegmans",
    color: "#006341",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  ralphs: {
    id: "ralphs",
    name: "Ralphs",
    color: "#CC0000",
    adapter: "kroger",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  shaws: {
    id: "shaws",
    name: "Shaw's",
    color: "#003087",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  star_market: {
    id: "star_market",
    name: "Star Market",
    color: "#CC0000",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  vons: {
    id: "vons",
    name: "Vons",
    color: "#0057A6",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  piggly_wiggly: {
    id: "piggly_wiggly",
    name: "Piggly Wiggly",
    color: "#CC0000",
    adapter: "metadata-only",
    supports_pricing: false,
    supports_products: false,
    supports_export: false,
  },
  weis: {
    id: "weis",
    name: "Weis Markets",
    color: "#003DA5",
    adapter: "basket",
    supports_pricing: true,
    supports_products: true,
    supports_export: false,
  },
  fresh_market: {
    id: "fresh_market",
    name: "Fresh Market",
    color: "#4A7C59",
    adapter: "metadata-only",
    supports_pricing: false,
    supports_products: false,
    supports_export: false,
  },
  natural_grocers: {
    id: "natural_grocers",
    name: "Natural Grocers",
    color: "#5B8C00",
    adapter: "metadata-only",
    supports_pricing: false,
    supports_products: false,
    supports_export: false,
  },
  instacart: {
    id: "instacart",
    name: "Instacart",
    color: "#43B02A",
    adapter: "metadata-only",
    supports_pricing: false,
    supports_products: false,
    supports_export: true,
  },
  shipt: {
    id: "shipt",
    name: "Shipt",
    color: "#CC0000",
    adapter: "metadata-only",
    supports_pricing: false,
    supports_products: false,
    supports_export: false,
  },
  amazon_fresh: {
    id: "amazon_fresh",
    name: "Amazon Fresh",
    color: "#FF9900",
    adapter: "metadata-only",
    supports_pricing: false,
    supports_products: false,
    supports_export: true,
  },
};

export const getStoreList = () => Object.values(STORES);
export const getStore = (id) => STORES[id];
export const getStoresWithPricing = () => getStoreList().filter(s => s.supports_pricing);
export const getStoresWithExport = () => getStoreList().filter(s => s.supports_export);